### ISSUE TITLE
nothing gets created on el6 when running will_ruby_raise

### ISSUE THREAD

**Issue by cristifalcas** [voxik/abrt-ruby#4]
It looks like the gem is working and is loaded, because when I run:
# will_ruby_raise

Will raise.
/usr/bin/will_ruby_raise:4:in `/': divided by 0 (ZeroDivisionError)
        from /usr/bin/will_ruby_raise:4

I see in /var/log/abrt.log this line:
2014-12-30T07:15:50.806200-05:00 machine.domain abrt[16433]: detected unhandled Ruby exception in '/usr/bin/will_ruby_raise'

But nothing gets created in /var/spool/abrt and no email is sent.

All other tests work (will_cpp_segfault, will_oops, will_python_raise, etc.), so I don't think it's a configuration  problem.

**Comment by cristi1979** [comment]
Any problems if I do a pull request for this? Meaning to cast exception.backtrace.last[0] to chr?

**Comment by voxik** [comment]
This should be resolved via 5fd45b1018a6d875ef49ff7b639d705a7bac2b43.
